// <auto-generated />
using AgrimanAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgrimanAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229064859_FixAmountPrecision")]
    partial class FixAmountPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgrimanAPI.Infrastructure.Entities.AgriThingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ThingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgriThings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ThingName = "Seeds"
                        },
                        new
                        {
                            Id = 2,
                            ThingName = "Soil"
                        },
                        new
                        {
                            Id = 3,
                            ThingName = "Water"
                        },
                        new
                        {
                            Id = 4,
                            ThingName = "Fertilizer"
                        },
                        new
                        {
                            Id = 5,
                            ThingName = "Manure"
                        },
                        new
                        {
                            Id = 6,
                            ThingName = "Pesticide"
                        },
                        new
                        {
                            Id = 7,
                            ThingName = "Form Machinery"
                        },
                        new
                        {
                            Id = 8,
                            ThingName = "Irrigation systems"
                        },
                        new
                        {
                            Id = 9,
                            ThingName = "Fungicide"
                        },
                        new
                        {
                            Id = 10,
                            ThingName = "Bio Fertilizer"
                        });
                });

            modelBuilder.Entity("AgrimanAPI.Infrastructure.Entities.AgriWorkEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AgriWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            WorkDescription = "Loosening and preparing the soil for cultivation",
                            WorkName = "Ploughing"
                        },
                        new
                        {
                            Id = 2,
                            WorkDescription = "Planting seeds into the prepared soil",
                            WorkName = "Sowing"
                        },
                        new
                        {
                            Id = 3,
                            WorkDescription = "Supplying water to crops at regular intervals",
                            WorkName = "Irrigation"
                        },
                        new
                        {
                            Id = 4,
                            WorkDescription = "Applying nutrients to improve crop growth",
                            WorkName = "Fertilization"
                        },
                        new
                        {
                            Id = 5,
                            WorkDescription = "Removing or controlling unwanted plants",
                            WorkName = "Weed Control"
                        },
                        new
                        {
                            Id = 6,
                            WorkDescription = "Spraying chemicals to control weeds and pests",
                            WorkName = "Herbicide Spraying"
                        },
                        new
                        {
                            Id = 7,
                            WorkDescription = "Collecting mature crops from the field",
                            WorkName = "Harvesting"
                        },
                        new
                        {
                            Id = 8,
                            WorkDescription = "Storing harvested crops safely to prevent damage",
                            WorkName = "Storage"
                        },
                        new
                        {
                            Id = 9,
                            WorkDescription = "Packing crops for transport or sale",
                            WorkName = "Packing"
                        },
                        new
                        {
                            Id = 10,
                            WorkDescription = "Sending agricultural products to other regions or countries",
                            WorkName = "Export"
                        });
                });

            modelBuilder.Entity("AgrimanAPI.Infrastructure.Entities.PackingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PackingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<int>("UnitAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Packings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PackingName = "GunningBag",
                            Unit = 1,
                            UnitAmount = 1000
                        },
                        new
                        {
                            Id = 2,
                            PackingName = "Kg",
                            Unit = 1,
                            UnitAmount = 100
                        });
                });

            modelBuilder.Entity("AgrimanAPI.Infrastructure.Entities.TransactionThingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AmountSpend")
                        .HasColumnType("real")
                        .HasColumnName("amount_spend");

                    b.Property<int>("ThingQuantity")
                        .HasColumnType("int")
                        .HasColumnName("thing_quantity");

                    b.Property<int>("ThingsId")
                        .HasColumnType("int")
                        .HasColumnName("things_id");

                    b.Property<string>("ThingsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("things_name");

                    b.HasKey("Id");

                    b.ToTable("transaction_things_details");
                });

            modelBuilder.Entity("AgrimanAPI.Infrastructure.Entities.TransactionWorkDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkId")
                        .HasColumnType("int");

                    b.Property<string>("WorkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkersCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transaction_Work_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
